version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.26.1
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      # Standard settings
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
      
      # Enable the text2vec-transformers module
      ENABLE_MODULES: "text2vec-transformers"
      DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
      TRANSFORMERS_INFERENCE_API: "http://t2v-transformers:8080"

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    restart: unless-stopped
    environment:
      # Set to "1" if you have a GPU with CUDA support; otherwise "0"
      ENABLE_CUDA: "0"
