version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      # Standard settings
      GRPC_ENABLED: 'true'
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'  # Allow anonymous access
      AUTHENTICATION_APIKEY_ENABLED: 'false'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
      GOOGLE_APIKEY: "AIzaSyDDa_oAOfp3-eazR7V6S4LR_gTBKiueQ3k"
      GENERATIVE_GOOGLE_APIKEY: "AIzaSyDDa_oAOfp3-eazR7V6S4LR_gTBKiueQ3k"
      GENERATIVE_GOOGLE_MODEL: "gemini-pro"

      # Enable both modules
      ENABLE_MODULES: "multi2vec-clip,text2vec-transformers,generative-google"
      
      # Default vectorizer module (you can choose one as default)
      DEFAULT_VECTORIZER_MODULE: "multi2vec-clip"

      # Multi2Vec-Clip module settings
      CLIP_INFERENCE_API: "http://multi2vec-clip:8080"

      # Text2Vec-Transformers module settings
      TRANSFORMERS_INFERENCE_API: "http://t2v-transformers:8080"

  multi2vec-clip:
    image: semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32-multilingual-v1
    restart: unless-stopped
    environment:
      ENABLE_CUDA: "0" # Set to "1" if you have a GPU with CUDA support

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    restart: unless-stopped
    environment:
      ENABLE_CUDA: "0" # Set to "1" if you have a GPU with CUDA support
